[pytest]
addopts = -ra
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths =
    tests/unit
    tests/streaming
    tests/webrtc
filterwarnings =
    ignore:.*'audioop' is deprecated and slated for removal in Python 3.13.*:DeprecationWarning
    ignore:.*'aifc' is deprecated and slated for removal in Python 3.13.*:DeprecationWarning
    ignore:.*'sunau' is deprecated and slated for removal in Python 3.13.*:DeprecationWarning
    ignore:.*return_token_timestamps is deprecated for WhisperFeatureExtractor.*:FutureWarning
    ignore:.*return_token_timestamps is deprecated for WhisperFeatureExtractor.*:UserWarning
