"""
Prometheus metrics endpoint for Grafana integration.

Exposes application metrics in Prometheus format for monitoring:
- HTTP request metrics
- Voice conversation metrics
- LLM inference metrics
- System resource metrics
"""

import os
import time
import logging
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, Response
from prometheus_client import (
    Counter,
    Histogram,
    Gauge,
    generate_latest,
    CONTENT_TYPE_LATEST,
    CollectorRegistry,
    multiprocess,
)

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Metrics"])


# ============================================================================
# Metric Definitions
# ============================================================================

# Use a custom registry if running in multiprocess mode
try:
    # Check if we're in multiprocess mode
    prometheus_multiproc_dir = os.environ.get("prometheus_multiproc_dir")
    if prometheus_multiproc_dir:
        registry = CollectorRegistry()
        multiprocess.MultiProcessCollector(registry)
    else:
        registry = None  # Use default registry
except Exception:
    registry = None

# HTTP Request Metrics
http_requests_total = Counter(
    "beautyai_http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status_code"],
)

http_request_duration_seconds = Histogram(
    "beautyai_http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "endpoint"],
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)

# Voice Conversation Metrics
voice_sessions_total = Counter(
    "beautyai_voice_sessions_total",
    "Total voice sessions started",
    ["endpoint", "language"],
)

voice_sessions_active = Gauge(
    "beautyai_voice_sessions_active",
    "Currently active voice sessions",
    ["endpoint"],
)

voice_message_duration_seconds = Histogram(
    "beautyai_voice_message_duration_seconds",
    "Voice message duration in seconds",
    ["language"],
    buckets=[0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 15.0, 30.0],
)

voice_response_time_seconds = Histogram(
    "beautyai_voice_response_time_seconds",
    "End-to-end voice response time (STT + LLM + TTS)",
    ["endpoint"],
    buckets=[0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 7.5, 10.0],
)

# STT/TTS Metrics
stt_processing_time_seconds = Histogram(
    "beautyai_stt_processing_time_seconds",
    "Speech-to-text processing time",
    ["model"],
    buckets=[0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0],
)

tts_processing_time_seconds = Histogram(
    "beautyai_tts_processing_time_seconds",
    "Text-to-speech processing time",
    ["engine"],
    buckets=[0.1, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0],
)

# LLM Inference Metrics
llm_requests_total = Counter(
    "beautyai_llm_requests_total",
    "Total LLM inference requests",
    ["model", "endpoint"],
)

llm_tokens_generated = Counter(
    "beautyai_llm_tokens_generated_total",
    "Total tokens generated by LLM",
    ["model"],
)

llm_inference_time_seconds = Histogram(
    "beautyai_llm_inference_time_seconds",
    "LLM inference time in seconds",
    ["model"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0],
)

# WebRTC Metrics
webrtc_connections_total = Counter(
    "beautyai_webrtc_connections_total",
    "Total WebRTC connections",
    ["status"],  # connected, disconnected, failed
)

webrtc_connections_active = Gauge(
    "beautyai_webrtc_connections_active",
    "Currently active WebRTC connections",
)

webrtc_ice_candidates = Counter(
    "beautyai_webrtc_ice_candidates_total",
    "Total ICE candidates exchanged",
    ["type"],  # host, srflx, relay
)

# SaaS Platform Metrics
active_users = Gauge(
    "beautyai_active_users",
    "Currently active users",
)

active_subscriptions = Gauge(
    "beautyai_active_subscriptions",
    "Active subscriptions by plan",
    ["plan"],
)

webchat_sessions_active = Gauge(
    "beautyai_webchat_sessions_active",
    "Currently active web chat sessions",
)

messages_processed_total = Counter(
    "beautyai_messages_processed_total",
    "Total messages processed",
    ["channel"],  # whatsapp, webchat, voice
)

# Knowledge Base Metrics
kb_documents_total = Gauge(
    "beautyai_kb_documents_total",
    "Total documents in knowledge bases",
    ["status"],
)

kb_search_requests_total = Counter(
    "beautyai_kb_search_requests_total",
    "Total knowledge base search requests",
)

kb_search_duration_seconds = Histogram(
    "beautyai_kb_search_duration_seconds",
    "Knowledge base search duration",
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
)

# System Metrics
gpu_memory_used_bytes = Gauge(
    "beautyai_gpu_memory_used_bytes",
    "GPU memory usage in bytes",
    ["device"],
)

gpu_utilization_percent = Gauge(
    "beautyai_gpu_utilization_percent",
    "GPU utilization percentage",
    ["device"],
)

model_loaded = Gauge(
    "beautyai_model_loaded",
    "Whether a model is currently loaded",
    ["model_name", "model_type"],
)


# ============================================================================
# Metric Collection Helpers
# ============================================================================

class MetricsCollector:
    """Helper class for recording metrics throughout the application."""
    
    @staticmethod
    def record_http_request(method: str, endpoint: str, status_code: int, duration: float):
        """Record an HTTP request."""
        http_requests_total.labels(
            method=method,
            endpoint=endpoint,
            status_code=str(status_code),
        ).inc()
        http_request_duration_seconds.labels(
            method=method,
            endpoint=endpoint,
        ).observe(duration)
    
    @staticmethod
    def record_voice_session_start(endpoint: str, language: str):
        """Record a new voice session."""
        voice_sessions_total.labels(endpoint=endpoint, language=language).inc()
        voice_sessions_active.labels(endpoint=endpoint).inc()
    
    @staticmethod
    def record_voice_session_end(endpoint: str):
        """Record voice session end."""
        voice_sessions_active.labels(endpoint=endpoint).dec()
    
    @staticmethod
    def record_voice_response(endpoint: str, duration: float):
        """Record voice response time."""
        voice_response_time_seconds.labels(endpoint=endpoint).observe(duration)
    
    @staticmethod
    def record_stt(model: str, duration: float):
        """Record STT processing."""
        stt_processing_time_seconds.labels(model=model).observe(duration)
    
    @staticmethod
    def record_tts(engine: str, duration: float):
        """Record TTS processing."""
        tts_processing_time_seconds.labels(engine=engine).observe(duration)
    
    @staticmethod
    def record_llm_request(model: str, endpoint: str, tokens: int, duration: float):
        """Record LLM inference."""
        llm_requests_total.labels(model=model, endpoint=endpoint).inc()
        llm_tokens_generated.labels(model=model).inc(tokens)
        llm_inference_time_seconds.labels(model=model).observe(duration)
    
    @staticmethod
    def record_webrtc_connection(status: str):
        """Record WebRTC connection event."""
        webrtc_connections_total.labels(status=status).inc()
        if status == "connected":
            webrtc_connections_active.inc()
        elif status == "disconnected":
            webrtc_connections_active.dec()
    
    @staticmethod
    def record_message(channel: str):
        """Record a processed message."""
        messages_processed_total.labels(channel=channel).inc()
    
    @staticmethod
    def record_kb_search(duration: float):
        """Record knowledge base search."""
        kb_search_requests_total.inc()
        kb_search_duration_seconds.observe(duration)
    
    @staticmethod
    def update_gpu_metrics():
        """Update GPU metrics from nvidia-smi."""
        try:
            import pynvml
            pynvml.nvmlInit()
            
            device_count = pynvml.nvmlDeviceGetCount()
            for i in range(device_count):
                handle = pynvml.nvmlDeviceGetHandleByIndex(i)
                memory_info = pynvml.nvmlDeviceGetMemoryInfo(handle)
                utilization = pynvml.nvmlDeviceGetUtilizationRates(handle)
                
                gpu_memory_used_bytes.labels(device=f"gpu{i}").set(memory_info.used)
                gpu_utilization_percent.labels(device=f"gpu{i}").set(utilization.gpu)
            
            pynvml.nvmlShutdown()
        except Exception as e:
            logger.debug(f"GPU metrics not available: {e}")


# Global collector instance
metrics_collector = MetricsCollector()


# ============================================================================
# Endpoints
# ============================================================================

@router.get("/metrics")
async def prometheus_metrics():
    """
    Prometheus metrics endpoint.
    
    Exposes all application metrics in Prometheus format.
    Configure your Prometheus server to scrape this endpoint.
    """
    # Update GPU metrics before returning
    MetricsCollector.update_gpu_metrics()
    
    # Generate metrics
    if registry:
        metrics = generate_latest(registry)
    else:
        metrics = generate_latest()
    
    return Response(
        content=metrics,
        media_type=CONTENT_TYPE_LATEST,
    )


@router.get("/metrics/json")
async def metrics_json():
    """
    JSON format metrics endpoint for debugging.
    
    Returns a subset of key metrics in JSON format.
    """
    # Collect current values (approximation, as Prometheus doesn't expose values easily)
    return {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "endpoints": {
            "prometheus": "/metrics",
            "json": "/metrics/json",
        },
        "info": {
            "description": "Use /metrics for full Prometheus-format metrics",
            "scrape_interval_recommended": "15s",
        },
    }


# ============================================================================
# Middleware Integration Example
# ============================================================================

async def metrics_middleware(request, call_next):
    """
    Middleware to automatically record HTTP metrics.
    
    Add this to your FastAPI app:
    app.middleware("http")(metrics_middleware)
    """
    start_time = time.time()
    response = await call_next(request)
    duration = time.time() - start_time
    
    # Skip metrics endpoint to avoid recursion
    if not request.url.path.startswith("/metrics"):
        metrics_collector.record_http_request(
            method=request.method,
            endpoint=request.url.path,
            status_code=response.status_code,
            duration=duration,
        )
    
    return response
