"""
SQLAlchemy models for WhatsApp Manager.

Defines all database tables for multi-tenant WhatsApp automation:
- User: SaaS platform authentication
- Customer: Business accounts (tenants)
- WhatsAppAccount: Connected WhatsApp Business accounts
- AgentConfig: AI agent configuration with system prompts
- Conversation: WhatsApp chat threads
- Message: Individual messages with source tracking
"""

import enum
from datetime import datetime, timedelta
from typing import Optional, List

from sqlalchemy import (
    Column, Integer, String, Text, Boolean, DateTime, 
    ForeignKey, Enum, UniqueConstraint, Index
)
from sqlalchemy.orm import relationship, Mapped, mapped_column
from sqlalchemy.sql import func

from .connection import Base


class MessageSource(enum.Enum):
    """Source of a message in a conversation."""
    CUSTOMER = "customer"  # From WhatsApp end-user
    AI = "ai"              # Generated by LLM
    HUMAN = "human"        # Manual intervention by business owner


class MessageStatus(enum.Enum):
    """WhatsApp message delivery status."""
    PENDING = "pending"
    SENT = "sent"
    DELIVERED = "delivered"
    READ = "read"
    FAILED = "failed"


class User(Base):
    """
    SaaS platform user account.
    
    Users can own multiple Customers (businesses).
    """
    __tablename__ = "users"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    customers: Mapped[List["Customer"]] = relationship("Customer", back_populates="user", lazy="selectin")
    
    def __repr__(self) -> str:
        return f"<User(id={self.id}, email='{self.email}')>"


class Customer(Base):
    """
    Business/tenant account.
    
    Each customer represents a business that uses the WhatsApp automation.
    A user can manage multiple customers (multi-tenant).
    """
    __tablename__ = "customers"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    
    # Relationships
    user: Mapped[Optional["User"]] = relationship("User", back_populates="customers")
    whatsapp_accounts: Mapped[List["WhatsAppAccount"]] = relationship("WhatsAppAccount", back_populates="customer", lazy="selectin")
    agent_config: Mapped[Optional["AgentConfig"]] = relationship("AgentConfig", back_populates="customer", uselist=False, lazy="selectin")
    
    def __repr__(self) -> str:
        return f"<Customer(id={self.id}, name='{self.name}')>"


class WhatsAppAccount(Base):
    """
    Connected WhatsApp Business account.
    
    Stores Meta API credentials from Embedded Signup flow.
    """
    __tablename__ = "whatsapp_accounts"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Meta/WhatsApp IDs
    phone_number_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    waba_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # WhatsApp Business Account ID
    
    # Credentials
    access_token: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Display info
    display_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    phone_number: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # Formatted phone number
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    verified_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="whatsapp_accounts")
    conversations: Mapped[List["Conversation"]] = relationship("Conversation", back_populates="whatsapp_account", lazy="selectin")
    
    def __repr__(self) -> str:
        return f"<WhatsAppAccount(id={self.id}, phone_number_id='{self.phone_number_id}')>"


class AgentConfig(Base):
    """
    AI agent configuration for a customer.
    
    Stores the system prompt template fields and compiled prompt.
    Only one config per customer (1:1 relationship).
    """
    __tablename__ = "agent_configs"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, unique=True)
    
    # Template fields
    business_name: Mapped[str] = mapped_column(String(255), nullable=False)
    tone: Mapped[str] = mapped_column(String(50), default="professional")  # professional, friendly, casual, formal
    behavior_rules: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    custom_instructions: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Override for power users
    
    # Compiled system prompt
    system_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    
    # AI behavior settings
    ai_enabled: Mapped[bool] = mapped_column(Boolean, default=True)
    ai_pause_until: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)  # NULL = active
    ai_pause_duration_minutes: Mapped[int] = mapped_column(Integer, default=30)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="agent_config")
    
    @classmethod
    def compile_system_prompt(
        cls,
        business_name: str,
        tone: str = "professional",
        behavior_rules: Optional[str] = None,
        custom_instructions: Optional[str] = None
    ) -> str:
        """
        Compile template fields into a system prompt string.
        
        If custom_instructions is provided, it overrides the template.
        """
        if custom_instructions:
            return custom_instructions.strip()
        
        tone_descriptions = {
            "professional": "professional and courteous",
            "friendly": "warm, friendly, and approachable",
            "casual": "relaxed and conversational",
            "formal": "formal and respectful"
        }
        tone_desc = tone_descriptions.get(tone, "professional and courteous")
        
        prompt_parts = [
            f"You are {business_name}'s AI assistant.",
            f"Communicate in a {tone_desc} manner.",
            "Be helpful, accurate, and concise in your responses.",
            "If you don't know something, say so honestly."
        ]
        
        if behavior_rules:
            prompt_parts.append(f"\nAdditional rules:\n{behavior_rules.strip()}")
        
        return "\n".join(prompt_parts)
    
    def is_ai_active(self) -> bool:
        """Check if AI responses are currently enabled."""
        if not self.ai_enabled:
            return False
        if self.ai_pause_until and self.ai_pause_until > datetime.utcnow():
            return False
        return True
    
    def pause_ai(self, minutes: Optional[int] = None) -> None:
        """Pause AI responses for the specified duration."""
        duration = minutes or self.ai_pause_duration_minutes
        self.ai_pause_until = datetime.utcnow() + timedelta(minutes=duration)
    
    def resume_ai(self) -> None:
        """Resume AI responses immediately."""
        self.ai_pause_until = None
    
    def __repr__(self) -> str:
        return f"<AgentConfig(id={self.id}, business_name='{self.business_name}')>"


class Conversation(Base):
    """
    WhatsApp conversation thread with an end customer.
    
    Each conversation is between a WhatsApp Business account and
    a single contact (identified by phone number).
    """
    __tablename__ = "conversations"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, index=True)
    whatsapp_account_id: Mapped[int] = mapped_column(Integer, ForeignKey("whatsapp_accounts.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Contact info
    contact_phone: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    contact_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    
    # Conversation state
    status: Mapped[str] = mapped_column(String(20), default="active")  # active, archived, blocked
    last_message_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, index=True)
    unread_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # Conversation-level AI pause (overrides agent config)
    ai_paused_until: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Unique constraint: one conversation per contact per account
    __table_args__ = (
        UniqueConstraint('whatsapp_account_id', 'contact_phone', name='uq_conversation_account_contact'),
        Index('ix_conversations_last_message', 'last_message_at', postgresql_using='btree'),
    )
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer")
    whatsapp_account: Mapped["WhatsAppAccount"] = relationship("WhatsAppAccount", back_populates="conversations")
    messages: Mapped[List["Message"]] = relationship("Message", back_populates="conversation", lazy="selectin", order_by="Message.created_at")
    
    def is_ai_active(self, agent_config: Optional["AgentConfig"] = None) -> bool:
        """Check if AI is active for this conversation."""
        # Conversation-level pause takes precedence
        if self.ai_paused_until and self.ai_paused_until > datetime.utcnow():
            return False
        # Fall back to agent config
        if agent_config:
            return agent_config.is_ai_active()
        return True
    
    def __repr__(self) -> str:
        return f"<Conversation(id={self.id}, contact='{self.contact_phone}')>"


class Message(Base):
    """
    Individual message in a conversation.
    
    Tracks source (customer/ai/human), delivery status, and content.
    """
    __tablename__ = "messages"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    conversation_id: Mapped[int] = mapped_column(Integer, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Content
    content: Mapped[str] = mapped_column(Text, nullable=False)
    media_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    media_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # image, audio, video, document
    
    # WhatsApp message ID
    whatsapp_message_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, index=True)
    
    # Source tracking
    source: Mapped[MessageSource] = mapped_column(Enum(MessageSource), nullable=False)
    
    # Delivery status
    status: Mapped[MessageStatus] = mapped_column(Enum(MessageStatus), default=MessageStatus.PENDING)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), index=True)
    
    # Relationships
    conversation: Mapped["Conversation"] = relationship("Conversation", back_populates="messages")
    
    def __repr__(self) -> str:
        preview = self.content[:30] + "..." if len(self.content) > 30 else self.content
        return f"<Message(id={self.id}, source={self.source.value}, preview='{preview}')>"
