"""
SQLAlchemy models for BeautyAI SaaS Platform.

Defines all database tables for multi-tenant WhatsApp + Web Chat automation:

Core Entities:
- User: SaaS platform authentication (with admin role for @gmai.sa domain)
- Customer: Business accounts (tenants)
- WhatsAppAccount: Connected WhatsApp Business accounts
- AgentConfig: AI agent configuration with system prompts
- Conversation: WhatsApp chat threads
- Message: Individual messages with source tracking

Subscription & Billing:
- Plan: Subscription plans with pricing and limits
- Subscription: Customer subscriptions with Stripe integration
- UsageEvent: Token/message usage tracking for metering

Knowledge Base (RAG):
- KnowledgeBase: Customer knowledge collections
- Document: Uploaded documents
- Chunk: Embedded text chunks with pgvector

Web Chat Widget:
- WidgetToken: API keys for embedding chat widget
- WebChatSession: Widget chat sessions
- WebChatMessage: Widget chat messages

Admin:
- AdminInvite: Invite codes for @gmai.sa admin onboarding
"""

import enum
import secrets
import hashlib
from datetime import datetime, timedelta, timezone
from typing import Optional, List, Any
from decimal import Decimal

from sqlalchemy import (
    Column, Integer, String, Text, Boolean, DateTime, 
    ForeignKey, Enum, UniqueConstraint, Index, Float,
    Numeric, JSON, LargeBinary
)
from sqlalchemy.types import TypeDecorator
from sqlalchemy.orm import relationship, Mapped, mapped_column
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

from .connection import Base

# Try to import pgvector, fall back gracefully if not installed
try:
    from pgvector.sqlalchemy import Vector
    PGVECTOR_AVAILABLE = True
except ImportError:
    Vector = None
    PGVECTOR_AVAILABLE = False


# ============================================================================
# Enums
# ============================================================================


class MessageSource(enum.Enum):
    """Source of a message in a conversation."""
    CUSTOMER = "customer"  # From WhatsApp end-user
    AI = "ai"              # Generated by LLM
    HUMAN = "human"        # Manual intervention by business owner


class MessageStatus(enum.Enum):
    """WhatsApp message delivery status."""
    PENDING = "pending"
    SENT = "sent"
    DELIVERED = "delivered"
    READ = "read"
    FAILED = "failed"


class UserRole(enum.Enum):
    """User roles for RBAC."""
    USER = "user"      # Regular customer
    ADMIN = "admin"    # Platform administrator (@gmai.sa domain)
    GUEST = "guest"    # Guest/Demo user (limited access)


class SubscriptionStatus(enum.Enum):
    """Subscription lifecycle status."""
    TRIAL = "trial"
    ACTIVE = "active"
    PAST_DUE = "past_due"
    CANCELED = "canceled"
    EXPIRED = "expired"


class UsageEventType(enum.Enum):
    """Types of usage events for metering."""
    WHATSAPP_MESSAGE_IN = "whatsapp_message_in"
    WHATSAPP_MESSAGE_OUT = "whatsapp_message_out"
    WEBCHAT_MESSAGE = "webchat_message"
    LLM_TOKENS = "llm_tokens"
    VOICE_MINUTES = "voice_minutes"
    RAG_QUERY = "rag_query"
    DOCUMENT_UPLOAD = "document_upload"


class DocumentStatus(enum.Enum):
    """Document processing status."""
    PENDING = "pending"
    PROCESSING = "processing"
    INDEXED = "indexed"
    FAILED = "failed"


class DemoRequestStatus(enum.Enum):
    """Demo request status."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


class StringEnumType(TypeDecorator):
    """
    Persist Enum values as strings in the database.
    Handles conversion between Python Enum objects and database strings.
    For Postgres, uses native ENUM type to avoid casting errors.
    """
    impl = String
    cache_ok = True

    def __init__(self, enum_class, name=None, **kwargs):
        self.enum_class = enum_class
        self.name = name
        super().__init__(**kwargs)

    def load_dialect_impl(self, dialect):
        if dialect.name == 'postgresql' and self.name:
            values = [e.value for e in self.enum_class]
            return dialect.type_descriptor(PG_ENUM(*values, name=self.name, create_type=False))
        else:
            return dialect.type_descriptor(String())

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        if isinstance(value, self.enum_class):
            return value.value
        return str(value)

    def process_result_value(self, value, dialect):
        if value is None:
            return None
        return self.enum_class(value)


# ============================================================================
# Core Entities
# ============================================================================


class User(Base):
    """
    SaaS platform user account.
    
    Users can own multiple Customers (businesses).
    Admin role is automatically assigned for @gmai.sa email domain.
    """
    __tablename__ = "users"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    
    # Role-based access control
    role: Mapped[UserRole] = mapped_column(StringEnumType(UserRole, name='userrole'), default=UserRole.USER)
    
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False)
    
    # Email verification
    verification_token: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    verification_token_expires: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Password reset
    reset_token: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    reset_token_expires: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Stripe integration
    stripe_customer_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, unique=True)
    
    # Guest/Demo fields
    demo_request_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("demo_requests.id", ondelete="SET NULL"), nullable=True, index=True)
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    max_conversations: Mapped[Optional[int]] = mapped_column(Integer, default=10, nullable=True)
    conversations_used: Mapped[int] = mapped_column(Integer, default=0)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    customers: Mapped[List["Customer"]] = relationship("Customer", back_populates="user", lazy="selectin")
    demo_request: Mapped[Optional["DemoRequest"]] = relationship("DemoRequest", foreign_keys=[demo_request_id], back_populates="created_user")
    
    def is_admin(self) -> bool:
        """Check if user has admin role."""
        return self.role == UserRole.ADMIN

    def is_guest(self) -> bool:
        """Check if user has guest role."""
        return self.role == UserRole.GUEST
    
    @classmethod
    def should_be_admin(cls, email: str) -> bool:
        """Check if email should automatically get admin role."""
        return email.lower().endswith("@gmai.sa")

    # Guest/Demo helper methods
    def is_expired(self) -> bool:
        """Check if demo access has expired (for guest users)."""
        if not self.expires_at:
            return False
        return datetime.now(timezone.utc).replace(tzinfo=None) > self.expires_at
    
    def is_limit_reached(self) -> bool:
        """Check if usage limit has been reached (for guest users)."""
        if self.max_conversations is None:
            return False
        return self.conversations_used >= self.max_conversations
    
    def can_access_demo(self) -> bool:
        """Check if user can currently access the demo."""
        if not self.is_guest():
            return True # Regular users/admins can access
        return self.is_active and not self.is_expired() and not self.is_limit_reached()
    
    def increment_conversations(self) -> None:
        """Increment conversation usage counter."""
        self.conversations_used += 1
    
    def days_remaining(self) -> int:
        """Calculate days remaining until expiry."""
        if not self.expires_at or self.is_expired():
            return 0
        delta = self.expires_at - datetime.now(timezone.utc).replace(tzinfo=None)
        return max(0, delta.days)
    
    def conversations_remaining(self) -> int:
        """Calculate conversations remaining."""
        if self.max_conversations is None:
            return 9999
        return max(0, self.max_conversations - self.conversations_used)
    
    def generate_verification_token(self) -> str:
        """Generate a new email verification token."""
        token = secrets.token_urlsafe(32)
        self.verification_token = hashlib.sha256(token.encode()).hexdigest()
        self.verification_token_expires = (datetime.now(timezone.utc) + timedelta(hours=24)).replace(tzinfo=None)
        return token  # Return unhashed token to send in email
    
    def verify_verification_token(self, token: str) -> bool:
        """Verify the email verification token."""
        if not self.verification_token or not self.verification_token_expires:
            return False
        if datetime.now(timezone.utc).replace(tzinfo=None) > self.verification_token_expires:
            return False
        token_hash = hashlib.sha256(token.encode()).hexdigest()
        return secrets.compare_digest(self.verification_token, token_hash)
    
    def generate_reset_token(self) -> str:
        """Generate a new password reset token."""
        token = secrets.token_urlsafe(32)
        self.reset_token = hashlib.sha256(token.encode()).hexdigest()
        self.reset_token_expires = (datetime.now(timezone.utc) + timedelta(hours=1)).replace(tzinfo=None)
        return token  # Return unhashed token to send in email
    
    def verify_reset_token(self, token: str) -> bool:
        """Verify the password reset token."""
        if not self.reset_token or not self.reset_token_expires:
            return False
        if datetime.now(timezone.utc).replace(tzinfo=None) > self.reset_token_expires:
            return False
        token_hash = hashlib.sha256(token.encode()).hexdigest()
        return secrets.compare_digest(self.reset_token, token_hash)
    
    def __repr__(self) -> str:
        return f"<User(id={self.id}, email='{self.email}', role={self.role.value})>"


class Customer(Base):
    """
    Business/tenant account.
    
    Each customer represents a business that uses the WhatsApp automation.
    A user can manage multiple customers (multi-tenant).
    """
    __tablename__ = "customers"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    
    # Business settings
    timezone: Mapped[str] = mapped_column(String(50), default="Asia/Riyadh")
    locale: Mapped[str] = mapped_column(String(10), default="ar-SA")
    
    # Widget customization (colors/logo only per requirements)
    widget_primary_color: Mapped[str] = mapped_column(String(7), default="#10B981")  # Emerald green
    widget_secondary_color: Mapped[str] = mapped_column(String(7), default="#F3F4F6")
    widget_logo_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    widget_greeting_message: Mapped[str] = mapped_column(String(500), default="مرحباً! كيف يمكنني مساعدتك اليوم؟")
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    user: Mapped[Optional["User"]] = relationship("User", back_populates="customers")
    whatsapp_accounts: Mapped[List["WhatsAppAccount"]] = relationship("WhatsAppAccount", back_populates="customer", lazy="selectin")
    agent_config: Mapped[Optional["AgentConfig"]] = relationship("AgentConfig", back_populates="customer", uselist=False, lazy="selectin")
    subscription: Mapped[Optional["Subscription"]] = relationship("Subscription", back_populates="customer", uselist=False, lazy="selectin")
    knowledge_bases: Mapped[List["KnowledgeBase"]] = relationship("KnowledgeBase", back_populates="customer", lazy="selectin")
    widget_tokens: Mapped[List["WidgetToken"]] = relationship("WidgetToken", back_populates="customer", lazy="selectin")
    usage_events: Mapped[List["UsageEvent"]] = relationship("UsageEvent", back_populates="customer", lazy="noload")
    webchat_sessions: Mapped[List["WebChatSession"]] = relationship("WebChatSession", back_populates="customer", lazy="noload")
    
    def __repr__(self) -> str:
        return f"<Customer(id={self.id}, name='{self.name}')>"


class WhatsAppAccount(Base):
    """
    Connected WhatsApp Business account.
    
    Stores Meta API credentials from Embedded Signup flow.
    """
    __tablename__ = "whatsapp_accounts"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Meta/WhatsApp IDs
    phone_number_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    waba_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # WhatsApp Business Account ID
    
    # Credentials
    access_token: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Display info
    display_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    phone_number: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # Formatted phone number
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    verified_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="whatsapp_accounts")
    conversations: Mapped[List["Conversation"]] = relationship("Conversation", back_populates="whatsapp_account", lazy="selectin")
    
    def __repr__(self) -> str:
        return f"<WhatsAppAccount(id={self.id}, phone_number_id='{self.phone_number_id}')>"


class BusinessType(enum.Enum):
    """Business type for configuration wizard."""
    RETAIL = "retail"
    SERVICES = "services"
    BOTH = "both"


class SupportedLanguage(enum.Enum):
    """Languages supported for AI responses."""
    ENGLISH = "english"
    ARABIC = "arabic"
    BOTH = "both"


class AgentConfig(Base):
    """
    AI agent configuration for a customer.
    
    Stores the system prompt template fields and compiled prompt.
    Only one config per customer (1:1 relationship).
    """
    __tablename__ = "agent_configs"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, unique=True)
    
    # Template fields
    business_name: Mapped[str] = mapped_column(String(255), nullable=False)
    tone: Mapped[str] = mapped_column(String(50), default="professional")  # professional, friendly, casual, formal
    behavior_rules: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    custom_instructions: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Override for power users
    
    # NEW: Wizard-based configuration fields
    # Step 1: Business Profile
    business_description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Brief about what the business does
    business_type: Mapped[Optional[str]] = mapped_column(String(20), default="services")  # retail, services, both
    supported_language: Mapped[str] = mapped_column(String(20), default="both")  # english, arabic, both
    website_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    
    # Step 2: Booking/Scheduling
    booking_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    booking_link: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)  # Calendly, Cal.com, etc.
    
    # Step 3: Policies (force AI to follow)
    business_policies: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Business policies the AI must follow
    
    # Compiled system prompt
    system_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    
    # AI behavior settings
    ai_enabled: Mapped[bool] = mapped_column(Boolean, default=True)
    ai_pause_until: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)  # NULL = active
    ai_pause_duration_minutes: Mapped[int] = mapped_column(Integer, default=30)
    
    # Wizard completion tracking
    wizard_completed: Mapped[bool] = mapped_column(Boolean, default=False)
    wizard_current_step: Mapped[int] = mapped_column(Integer, default=1)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="agent_config")
    services: Mapped[List["BusinessService"]] = relationship("BusinessService", back_populates="agent_config", cascade="all, delete-orphan", lazy="selectin")
    products: Mapped[List["BusinessProduct"]] = relationship("BusinessProduct", back_populates="agent_config", cascade="all, delete-orphan", lazy="selectin")
    locations: Mapped[List["BusinessLocation"]] = relationship("BusinessLocation", back_populates="agent_config", cascade="all, delete-orphan", lazy="selectin")
    promotions: Mapped[List["BusinessPromotion"]] = relationship("BusinessPromotion", back_populates="agent_config", cascade="all, delete-orphan", lazy="selectin")
    
    @classmethod
    def compile_system_prompt(
        cls,
        business_name: str,
        tone: str = "professional",
        behavior_rules: Optional[str] = None,
        custom_instructions: Optional[str] = None,
        # NEW: Wizard-based fields
        business_description: Optional[str] = None,
        business_type: Optional[str] = None,
        supported_language: str = "both",
        website_url: Optional[str] = None,
        booking_enabled: bool = False,
        booking_link: Optional[str] = None,
        business_policies: Optional[str] = None,
        services: Optional[List[dict]] = None,
        products: Optional[List[dict]] = None,
        locations: Optional[List[dict]] = None,
        promotions: Optional[List[dict]] = None,
    ) -> str:
        """
        Compile template fields into a system prompt string.
        
        If custom_instructions is provided, it overrides the template.
        Generates locale-specific prompts based on supported_language.
        """
        if custom_instructions:
            return custom_instructions.strip()
        
        tone_descriptions = {
            "professional": "professional and courteous",
            "friendly": "warm, friendly, and approachable",
            "casual": "relaxed and conversational",
            "formal": "formal and respectful"
        }
        tone_desc = tone_descriptions.get(tone, "professional and courteous")
        
        # Language-specific instructions
        language_instructions = {
            "english": "Respond ONLY in English. Do not use Arabic.",
            "arabic": "أجب باللغة العربية فقط. لا تستخدم اللغة الإنجليزية. Respond ONLY in Arabic.",
            "both": "Respond in the same language the customer uses. If they write in Arabic, respond in Arabic. If they write in English, respond in English. You are fluent in both Arabic and English."
        }
        lang_instruction = language_instructions.get(supported_language, language_instructions["both"])
        
        prompt_parts = [
            f"You are {business_name}'s AI assistant.",
            f"Communicate in a {tone_desc} manner.",
            "",
            f"## Language Instructions",
            lang_instruction,
            "",
            "Be helpful, accurate, and concise in your responses.",
            "If you don't know something, say so honestly."
        ]
        
        # Add business description
        if business_description:
            prompt_parts.extend([
                "",
                "## About the Business",
                business_description.strip()
            ])
        
        # Add website
        if website_url:
            prompt_parts.extend([
                "",
                f"Website: {website_url}"
            ])
        
        # Add services (for service-based businesses)
        if services and business_type in ["services", "both"]:
            prompt_parts.extend([
                "",
                "## Services Offered",
                "| Service | Description | Price | Duration | Warranty |",
                "|---------|-------------|-------|----------|----------|"
            ])
            for svc in services:
                name = svc.get("name", "")
                desc = svc.get("description", "")
                price = svc.get("price_display", "")
                duration = svc.get("duration_minutes", "")
                warranty = svc.get("warranty", "")
                prompt_parts.append(f"| {name} | {desc} | {price} | {duration} min | {warranty} |")
        
        # Add products (for retail businesses)
        if products and business_type in ["retail", "both"]:
            prompt_parts.extend([
                "",
                "## Products Available",
                "| Product | Description | Price Range | Warranty | Shipping |",
                "|---------|-------------|-------------|----------|----------|"
            ])
            for prod in products:
                name = prod.get("name", "")
                desc = prod.get("description", "")
                price_range = prod.get("price_range", "")
                warranty = prod.get("warranty", "")
                shipping = prod.get("shipping_cost", "")
                prompt_parts.append(f"| {name} | {desc} | {price_range} | {warranty} | {shipping} |")
        
        # Add locations
        if locations:
            prompt_parts.extend([
                "",
                "## Business Locations",
                "| Branch | Address | Working Hours | Contact |",
                "|--------|---------|---------------|---------|"
            ])
            for loc in locations:
                branch = loc.get("branch_name", "")
                address = loc.get("address", "")
                hours = loc.get("working_hours", "")
                contact = loc.get("contact_number", "")
                prompt_parts.append(f"| {branch} | {address} | {hours} | {contact} |")
        
        # Add booking information
        if booking_enabled and booking_link:
            prompt_parts.extend([
                "",
                "## Appointments & Booking",
                f"Customers can book appointments at: {booking_link}",
                "When customers ask about scheduling, direct them to the booking link."
            ])
        
        # Add active promotions
        if promotions:
            active_promos = [p for p in promotions if p.get("is_active", True)]
            if active_promos:
                prompt_parts.extend([
                    "",
                    "## Current Promotions",
                    "Share these promotions when relevant to the customer's inquiry:"
                ])
                for promo in active_promos:
                    title = promo.get("title", "")
                    desc = promo.get("description", "")
                    valid_until = promo.get("valid_until", "")
                    prompt_parts.append(f"- **{title}**: {desc}")
                    if valid_until:
                        prompt_parts.append(f"  (Valid until: {valid_until})")
        
        # Add business policies (MUST FOLLOW)
        if business_policies:
            prompt_parts.extend([
                "",
                "## Business Policies (MUST FOLLOW)",
                "You MUST adhere to these business policies at all times:",
                business_policies.strip()
            ])
        
        # Add additional behavior rules
        if behavior_rules:
            prompt_parts.extend([
                "",
                "## Additional Guidelines",
                behavior_rules.strip()
            ])
        
        return "\n".join(prompt_parts)
    
    def is_ai_active(self) -> bool:
        """Check if AI responses are currently enabled."""
        if not self.ai_enabled:
            return False
        if self.ai_pause_until and self.ai_pause_until > datetime.utcnow():
            return False
        return True
    
    def pause_ai(self, minutes: Optional[int] = None) -> None:
        """Pause AI responses for the specified duration."""
        duration = minutes or self.ai_pause_duration_minutes
        self.ai_pause_until = datetime.utcnow() + timedelta(minutes=duration)
    
    def resume_ai(self) -> None:
        """Resume AI responses immediately."""
        self.ai_pause_until = None
    
    def __repr__(self) -> str:
        return f"<AgentConfig(id={self.id}, business_name='{self.business_name}')>"


# ============================================================================
# Business Configuration (Wizard-based)
# ============================================================================


class BusinessService(Base):
    """
    Services offered by a business (for service-based businesses).
    
    Used by the AI to provide accurate service information to customers.
    """
    __tablename__ = "business_services"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    agent_config_id: Mapped[int] = mapped_column(Integer, ForeignKey("agent_configs.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Service details
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    price: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    price_display: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # e.g., "SAR 100", "From SAR 50"
    duration_minutes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)  # Service duration
    warranty: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)  # Warranty info
    
    # Booking integration
    is_bookable: Mapped[bool] = mapped_column(Boolean, default=True)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    sort_order: Mapped[int] = mapped_column(Integer, default=0)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    agent_config: Mapped["AgentConfig"] = relationship("AgentConfig", back_populates="services")
    
    def to_dict(self) -> dict:
        """Convert to dictionary for prompt compilation."""
        return {
            "name": self.name,
            "description": self.description or "",
            "price": self.price,
            "price_display": self.price_display or "",
            "duration_minutes": self.duration_minutes or "",
            "warranty": self.warranty or "",
            "is_bookable": self.is_bookable,
        }
    
    def __repr__(self) -> str:
        return f"<BusinessService(id={self.id}, name='{self.name}')>"


class BusinessProduct(Base):
    """
    Products sold by a business (for retail businesses).
    
    Used by the AI to provide accurate product information to customers.
    """
    __tablename__ = "business_products"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    agent_config_id: Mapped[int] = mapped_column(Integer, ForeignKey("agent_configs.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Product details
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    price_min: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    price_max: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    price_range: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # e.g., "SAR 100 - 200"
    warranty: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    shipping_cost: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # e.g., "Free", "SAR 25"
    
    # Status
    is_available: Mapped[bool] = mapped_column(Boolean, default=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    sort_order: Mapped[int] = mapped_column(Integer, default=0)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    agent_config: Mapped["AgentConfig"] = relationship("AgentConfig", back_populates="products")
    
    def to_dict(self) -> dict:
        """Convert to dictionary for prompt compilation."""
        return {
            "name": self.name,
            "description": self.description or "",
            "price_range": self.price_range or "",
            "warranty": self.warranty or "",
            "shipping_cost": self.shipping_cost or "",
            "is_available": self.is_available,
        }
    
    def __repr__(self) -> str:
        return f"<BusinessProduct(id={self.id}, name='{self.name}')>"


class BusinessLocation(Base):
    """
    Physical locations/branches of a business.
    
    Used by the AI to direct customers to the right location.
    """
    __tablename__ = "business_locations"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    agent_config_id: Mapped[int] = mapped_column(Integer, ForeignKey("agent_configs.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Location details
    branch_name: Mapped[str] = mapped_column(String(255), nullable=False)
    address: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    city: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    google_maps_link: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    
    # Working hours (stored as JSON for flexibility)
    # Format: {"sunday": {"open": "09:00", "close": "18:00"}, ...}
    working_hours: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Human readable or JSON
    working_hours_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    
    # Contact
    contact_number: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    extension: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    whatsapp_number: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    
    # Status
    is_main_branch: Mapped[bool] = mapped_column(Boolean, default=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    sort_order: Mapped[int] = mapped_column(Integer, default=0)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    agent_config: Mapped["AgentConfig"] = relationship("AgentConfig", back_populates="locations")
    
    def to_dict(self) -> dict:
        """Convert to dictionary for prompt compilation."""
        return {
            "branch_name": self.branch_name,
            "address": self.address or "",
            "city": self.city or "",
            "working_hours": self.working_hours or "",
            "contact_number": self.contact_number or "",
            "google_maps_link": self.google_maps_link or "",
        }
    
    def __repr__(self) -> str:
        return f"<BusinessLocation(id={self.id}, branch_name='{self.branch_name}')>"


class BusinessPromotion(Base):
    """
    Active promotions and special offers.
    
    AI can share these promotions when relevant to customer inquiries.
    """
    __tablename__ = "business_promotions"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    agent_config_id: Mapped[int] = mapped_column(Integer, ForeignKey("agent_configs.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Promotion details
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    discount_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # percentage, fixed, bogo
    discount_value: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)  # "20%", "SAR 50"
    
    # Conditions
    terms_conditions: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    promo_code: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    
    # Validity
    valid_from: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    valid_until: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    sort_order: Mapped[int] = mapped_column(Integer, default=0)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    agent_config: Mapped["AgentConfig"] = relationship("AgentConfig", back_populates="promotions")
    
    def is_currently_valid(self) -> bool:
        """Check if promotion is currently valid based on dates."""
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        if self.valid_from and now < self.valid_from:
            return False
        if self.valid_until and now > self.valid_until:
            return False
        return self.is_active
    
    def to_dict(self) -> dict:
        """Convert to dictionary for prompt compilation."""
        return {
            "title": self.title,
            "description": self.description or "",
            "discount_value": self.discount_value or "",
            "promo_code": self.promo_code or "",
            "valid_until": self.valid_until.strftime("%Y-%m-%d") if self.valid_until else "",
            "is_active": self.is_currently_valid(),
        }
    
    def __repr__(self) -> str:
        return f"<BusinessPromotion(id={self.id}, title='{self.title}')>"


class Conversation(Base):
    """
    WhatsApp conversation thread with an end customer.
    
    Each conversation is between a WhatsApp Business account and
    a single contact (identified by phone number).
    """
    __tablename__ = "conversations"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, index=True)
    whatsapp_account_id: Mapped[int] = mapped_column(Integer, ForeignKey("whatsapp_accounts.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Contact info
    contact_phone: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    contact_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    
    # Conversation state
    status: Mapped[str] = mapped_column(String(20), default="active")  # active, archived, blocked
    last_message_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, index=True)
    unread_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # Conversation-level AI pause (overrides agent config)
    ai_paused_until: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Unique constraint: one conversation per contact per account
    __table_args__ = (
        UniqueConstraint('whatsapp_account_id', 'contact_phone', name='uq_conversation_account_contact'),
        Index('ix_conversations_last_message', 'last_message_at', postgresql_using='btree'),
    )
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer")
    whatsapp_account: Mapped["WhatsAppAccount"] = relationship("WhatsAppAccount", back_populates="conversations")
    messages: Mapped[List["Message"]] = relationship("Message", back_populates="conversation", lazy="selectin", order_by="Message.created_at")
    
    def is_ai_active(self, agent_config: Optional["AgentConfig"] = None) -> bool:
        """Check if AI is active for this conversation."""
        # Conversation-level pause takes precedence
        if self.ai_paused_until and self.ai_paused_until > datetime.utcnow():
            return False
        # Fall back to agent config
        if agent_config:
            return agent_config.is_ai_active()
        return True
    
    def __repr__(self) -> str:
        return f"<Conversation(id={self.id}, contact='{self.contact_phone}')>"


class Message(Base):
    """
    Individual message in a conversation.
    
    Tracks source (customer/ai/human), delivery status, and content.
    """
    __tablename__ = "messages"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    conversation_id: Mapped[int] = mapped_column(Integer, ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Content
    content: Mapped[str] = mapped_column(Text, nullable=False)
    media_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    media_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)  # image, audio, video, document
    
    # WhatsApp message ID
    whatsapp_message_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, index=True)
    
    # Source tracking
    source: Mapped[MessageSource] = mapped_column(StringEnumType(MessageSource, name='messagesource'), nullable=False)
    
    # Delivery status
    status: Mapped[MessageStatus] = mapped_column(StringEnumType(MessageStatus, name='messagestatus'), default=MessageStatus.PENDING)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), index=True)
    
    # Relationships
    conversation: Mapped["Conversation"] = relationship("Conversation", back_populates="messages")
    
    def __repr__(self) -> str:
        preview = self.content[:30] + "..." if len(self.content) > 30 else self.content
        return f"<Message(id={self.id}, source={self.source.value}, preview='{preview}')>"


# ============================================================================
# Subscription & Billing (Stripe Integration)
# ============================================================================


class Plan(Base):
    """
    Subscription plans with pricing and usage limits.
    """
    __tablename__ = "plans"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Plan identity
    name: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    stripe_price_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, unique=True)
    
    # Pricing (SAR)
    price_monthly: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    price_yearly: Mapped[Optional[Decimal]] = mapped_column(Numeric(10, 2), nullable=True)
    
    # Usage limits (per month)
    message_limit: Mapped[int] = mapped_column(Integer, default=1000)
    token_limit: Mapped[int] = mapped_column(Integer, default=100000)
    whatsapp_accounts_limit: Mapped[int] = mapped_column(Integer, default=1)
    knowledge_base_docs_limit: Mapped[int] = mapped_column(Integer, default=10)
    
    # Features JSON (flexible feature flags)
    features: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_public: Mapped[bool] = mapped_column(Boolean, default=True)  # Show in pricing page
    
    # Ordering
    sort_order: Mapped[int] = mapped_column(Integer, default=0)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    subscriptions: Mapped[List["Subscription"]] = relationship("Subscription", back_populates="plan", lazy="noload")
    
    def __repr__(self) -> str:
        return f"<Plan(id={self.id}, name='{self.name}', price={self.price_monthly} SAR)>"


class Subscription(Base):
    """
    Customer subscription with Stripe integration.
    """
    __tablename__ = "subscriptions"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, unique=True)
    plan_id: Mapped[int] = mapped_column(Integer, ForeignKey("plans.id", ondelete="RESTRICT"), nullable=False)
    
    # Stripe identifiers
    stripe_subscription_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, unique=True)
    
    # Status
    status: Mapped[SubscriptionStatus] = mapped_column(StringEnumType(SubscriptionStatus, name='subscriptionstatus'), default=SubscriptionStatus.TRIAL)
    
    # Billing period
    current_period_start: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    current_period_end: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    trial_ends_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Usage tracking (reset each period)
    messages_used: Mapped[int] = mapped_column(Integer, default=0)
    tokens_used: Mapped[int] = mapped_column(Integer, default=0)
    
    # Cancellation
    cancel_at_period_end: Mapped[bool] = mapped_column(Boolean, default=False)
    canceled_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="subscription")
    plan: Mapped["Plan"] = relationship("Plan", back_populates="subscriptions", lazy="selectin")
    
    def is_active(self) -> bool:
        """Check if subscription allows service usage."""
        if self.status in [SubscriptionStatus.ACTIVE, SubscriptionStatus.TRIAL]:
            return datetime.now(timezone.utc).replace(tzinfo=None) < self.current_period_end
        return False
    
    def has_message_quota(self) -> bool:
        """Check if message limit is not exceeded."""
        return self.messages_used < self.plan.message_limit
    
    def has_token_quota(self) -> bool:
        """Check if token limit is not exceeded."""
        return self.tokens_used < self.plan.token_limit
    
    def __repr__(self) -> str:
        return f"<Subscription(id={self.id}, customer_id={self.customer_id}, status={self.status.value})>"


class UsageEvent(Base):
    """
    Usage event tracking for billing and analytics.
    """
    __tablename__ = "usage_events"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Event details
    event_type: Mapped[UsageEventType] = mapped_column(StringEnumType(UsageEventType, name='usageeventtype'), nullable=False)
    quantity: Mapped[int] = mapped_column(Integer, default=1)
    
    # Optional metadata
    event_metadata: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), index=True)
    
    __table_args__ = (
        Index('ix_usage_events_customer_type_date', 'customer_id', 'event_type', 'created_at'),
    )
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="usage_events")
    
    def __repr__(self) -> str:
        return f"<UsageEvent(id={self.id}, type={self.event_type.value}, qty={self.quantity})>"


# ============================================================================
# Knowledge Base (RAG with pgvector)
# ============================================================================


class KnowledgeBase(Base):
    """
    Customer knowledge base collection for RAG.
    """
    __tablename__ = "knowledge_bases"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # KB identity
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Embedding settings
    embedding_model: Mapped[str] = mapped_column(String(100), default="text-embedding-3-small")
    embedding_dimensions: Mapped[int] = mapped_column(Integer, default=1536)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    __table_args__ = (
        UniqueConstraint('customer_id', 'name', name='uq_kb_customer_name'),
    )
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="knowledge_bases")
    documents: Mapped[List["Document"]] = relationship("Document", back_populates="knowledge_base", lazy="selectin", cascade="all, delete-orphan")
    
    def __repr__(self) -> str:
        return f"<KnowledgeBase(id={self.id}, name='{self.name}')>"


class Document(Base):
    """
    Uploaded document for knowledge base.
    """
    __tablename__ = "documents"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    knowledge_base_id: Mapped[int] = mapped_column(Integer, ForeignKey("knowledge_bases.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Document identity
    filename: Mapped[str] = mapped_column(String(500), nullable=False)
    original_filename: Mapped[str] = mapped_column(String(500), nullable=False)
    content_type: Mapped[str] = mapped_column(String(100), nullable=False)
    file_size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    
    # Content hash for deduplication
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    
    # Processing status
    status: Mapped[DocumentStatus] = mapped_column(StringEnumType(DocumentStatus, name='documentstatus'), default=DocumentStatus.PENDING)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Stats
    chunk_count: Mapped[int] = mapped_column(Integer, default=0)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    processed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Relationships
    knowledge_base: Mapped["KnowledgeBase"] = relationship("KnowledgeBase", back_populates="documents")
    chunks: Mapped[List["Chunk"]] = relationship("Chunk", back_populates="document", lazy="noload", cascade="all, delete-orphan")
    
    def __repr__(self) -> str:
        return f"<Document(id={self.id}, filename='{self.original_filename}', status={self.status.value})>"


class Chunk(Base):
    """
    Text chunk with embedding for vector search.
    
    Uses pgvector for similarity search.
    """
    __tablename__ = "chunks"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    document_id: Mapped[int] = mapped_column(Integer, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Chunk content
    text: Mapped[str] = mapped_column(Text, nullable=False)
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)  # Order within document
    
    # Metadata
    chunk_metadata: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    token_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # Embedding vector - stored as JSON array (pgvector column added via migration if available)
    # When pgvector is available, use: embedding = Column(Vector(1536))
    embedding_json: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    
    __table_args__ = (
        Index('ix_chunks_document_index', 'document_id', 'chunk_index'),
    )
    
    # Relationships
    document: Mapped["Document"] = relationship("Document", back_populates="chunks")
    
    def __repr__(self) -> str:
        preview = self.text[:50] + "..." if len(self.text) > 50 else self.text
        return f"<Chunk(id={self.id}, doc_id={self.document_id}, preview='{preview}')>"


# Add pgvector column if available (added via Alembic migration)
if PGVECTOR_AVAILABLE and Vector is not None:
    Chunk.embedding = Column(Vector(1536), nullable=True)


# ============================================================================
# Web Chat Widget
# ============================================================================


class WidgetToken(Base):
    """
    API tokens for embedding chat widget on customer websites.
    """
    __tablename__ = "widget_tokens"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Token identity
    name: Mapped[str] = mapped_column(String(100), nullable=False)  # e.g., "Production", "Staging"
    token_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True, index=True)
    token_prefix: Mapped[str] = mapped_column(String(8), nullable=False)  # For identification without exposing full token
    
    # Security settings
    domain_whitelist: Mapped[Optional[List[str]]] = mapped_column(ARRAY(String(255)), nullable=True)  # NULL = allow all
    rate_limit_per_minute: Mapped[int] = mapped_column(Integer, default=60)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    
    # Usage tracking
    last_used_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    request_count: Mapped[int] = mapped_column(Integer, default=0)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="widget_tokens")
    
    @classmethod
    def generate_token(cls) -> tuple[str, str, str]:
        """
        Generate a new widget token.
        
        Returns: (full_token, token_hash, token_prefix)
        """
        token = f"wt_{secrets.token_urlsafe(32)}"
        token_hash = hashlib.sha256(token.encode()).hexdigest()
        token_prefix = token[:10]
        return token, token_hash, token_prefix
    
    @classmethod
    def hash_token(cls, token: str) -> str:
        """Hash a token for lookup."""
        return hashlib.sha256(token.encode()).hexdigest()
    
    def is_valid(self) -> bool:
        """Check if token is valid for use."""
        if not self.is_active:
            return False
        if self.expires_at and datetime.now(timezone.utc).replace(tzinfo=None) > self.expires_at:
            return False
        return True
    
    def is_domain_allowed(self, domain: str) -> bool:
        """Check if request domain is whitelisted."""
        if not self.domain_whitelist:
            return True  # No whitelist = allow all
        return domain.lower() in [d.lower() for d in self.domain_whitelist]
    
    def __repr__(self) -> str:
        return f"<WidgetToken(id={self.id}, prefix='{self.token_prefix}...', active={self.is_active})>"


class WebChatSession(Base):
    """
    Chat session for website widget visitors.
    """
    __tablename__ = "webchat_sessions"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customer_id: Mapped[int] = mapped_column(Integer, ForeignKey("customers.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Session identity
    session_token: Mapped[str] = mapped_column(String(64), nullable=False, unique=True, index=True)
    
    # Visitor info (optional, for analytics)
    visitor_id: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)  # Browser fingerprint or cookie ID
    visitor_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    visitor_email: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    
    # Context
    page_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    referrer: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    user_agent: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    ip_address: Mapped[Optional[str]] = mapped_column(String(45), nullable=True)  # IPv6 compatible
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    last_message_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    
    __table_args__ = (
        Index('ix_webchat_sessions_customer_active', 'customer_id', 'is_active'),
    )
    
    # Relationships
    customer: Mapped["Customer"] = relationship("Customer", back_populates="webchat_sessions")
    messages: Mapped[List["WebChatMessage"]] = relationship("WebChatMessage", back_populates="session", lazy="selectin", order_by="WebChatMessage.created_at", cascade="all, delete-orphan")
    
    @classmethod
    def generate_session_token(cls) -> str:
        """Generate a unique session token."""
        return secrets.token_urlsafe(48)
    
    def is_valid(self) -> bool:
        """Check if session is still valid."""
        if not self.is_active:
            return False
        return datetime.now(timezone.utc).replace(tzinfo=None) < self.expires_at
    
    def __repr__(self) -> str:
        return f"<WebChatSession(id={self.id}, customer_id={self.customer_id}, active={self.is_active})>"


class WebChatMessage(Base):
    """
    Message in a web chat session.
    """
    __tablename__ = "webchat_messages"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[int] = mapped_column(Integer, ForeignKey("webchat_sessions.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Content
    content: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Role: user (visitor) or assistant (AI)
    role: Mapped[str] = mapped_column(String(20), nullable=False)  # "user" or "assistant"
    
    # Token usage (for metering)
    input_tokens: Mapped[int] = mapped_column(Integer, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, default=0)
    
    # Metadata
    message_metadata: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), index=True)
    
    # Relationships
    session: Mapped["WebChatSession"] = relationship("WebChatSession", back_populates="messages")
    
    def __repr__(self) -> str:
        preview = self.content[:30] + "..." if len(self.content) > 30 else self.content
        return f"<WebChatMessage(id={self.id}, role={self.role}, preview='{preview}')>"


# ============================================================================
# Admin
# ============================================================================


class AdminInvite(Base):
    """
    Invite codes for admin onboarding.
    
    Only users with @gmai.sa email can use invites to become admins.
    """
    __tablename__ = "admin_invites"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Invite identity
    code: Mapped[str] = mapped_column(String(64), nullable=False, unique=True, index=True)
    
    # Created by
    created_by_user_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    
    # Usage
    max_uses: Mapped[int] = mapped_column(Integer, default=1)
    use_count: Mapped[int] = mapped_column(Integer, default=0)
    
    # Target email (optional - restrict to specific email)
    target_email: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    @classmethod
    def generate_code(cls) -> str:
        """Generate a unique invite code."""
        return f"admin_{secrets.token_urlsafe(24)}"
    
    def is_valid(self, email: Optional[str] = None) -> bool:
        """Check if invite is valid for use."""
        if not self.is_active:
            return False
        if self.use_count >= self.max_uses:
            return False
        if self.expires_at and datetime.now(timezone.utc).replace(tzinfo=None) > self.expires_at:
            return False
        if self.target_email and email and email.lower() != self.target_email.lower():
            return False
        return True
    
    def use(self) -> None:
        """Mark invite as used."""
        self.use_count += 1
        if self.use_count >= self.max_uses:
            self.is_active = False
    
    def __repr__(self) -> str:
        return f"<AdminInvite(id={self.id}, uses={self.use_count}/{self.max_uses}, active={self.is_active})>"


# ============================================================================
# Demo Request System
# ============================================================================


class DemoRequest(Base):
    """
    Demo request submitted from website contact form.
    
    Users submit demo requests which admins can approve/reject.
    Upon approval, a GuestUser account is created with limited demo access.
    """
    __tablename__ = "demo_requests"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Contact info from form (firstName, lastName, email, phone, company, companySize, message)
    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    email: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    phone: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    company: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    company_size: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Status and admin actions
    status: Mapped[DemoRequestStatus] = mapped_column(
        StringEnumType(DemoRequestStatus, name='demo_request_status'),
        default=DemoRequestStatus.PENDING,
        index=True
    )
    admin_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    assigned_to_admin_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    scheduled_follow_up: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Timestamps
    submitted_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    reviewed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    assigned_to_admin: Mapped[Optional["User"]] = relationship("User", foreign_keys=[assigned_to_admin_id], lazy="selectin")
    created_user: Mapped[Optional["User"]] = relationship("User", foreign_keys="[User.demo_request_id]", back_populates="demo_request", uselist=False)
    guest_user: Mapped[Optional["GuestUser"]] = relationship("GuestUser", back_populates="demo_request", uselist=False, lazy="selectin")
    
    def full_name(self) -> str:
        """Get full name of the requester."""
        return f"{self.first_name} {self.last_name}"
    
    def __repr__(self) -> str:
        return f"<DemoRequest(id={self.id}, email='{self.email}', status={self.status.value})>"


class GuestUser(Base):
    """
    Guest user account with limited demo access.
    
    Created when admin approves a DemoRequest.
    Has time-limited and usage-limited access to voice demo.
    
    Authentication Flow:
    1. Admin approves demo request → GuestUser created with setup_token
    2. User clicks email link with setup_token → validates token, sets password
    3. After password set → setup_token invalidated, is_activated=True
    4. Subsequent logins use email + password (no token needed)
    """
    __tablename__ = "guest_users"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    demo_request_id: Mapped[int] = mapped_column(Integer, ForeignKey("demo_requests.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True, index=True)
    
    # Password-based authentication (set during account activation)
    password_hash: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    is_activated: Mapped[bool] = mapped_column(Boolean, default=False)
    
    # Setup token for initial account activation (short-lived, 1 hour)
    # This replaces the old access_token for initial login
    setup_token: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, unique=True, index=True)
    setup_token_expires: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Legacy access token - kept for backward compatibility during migration
    # Will be deprecated after all users have migrated to password auth
    access_token: Mapped[str] = mapped_column(String(255), nullable=False, unique=True, index=True)
    
    # Access limits
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    max_conversations: Mapped[int] = mapped_column(Integer, default=10)
    conversations_used: Mapped[int] = mapped_column(Integer, default=0)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    
    # Timestamps
    granted_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    last_used_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    demo_request: Mapped["DemoRequest"] = relationship("DemoRequest", back_populates="guest_user", lazy="selectin")
    
    def is_expired(self) -> bool:
        """Check if demo access has expired."""
        return datetime.now(timezone.utc).replace(tzinfo=None) > self.expires_at
    
    def is_limit_reached(self) -> bool:
        """Check if usage limit has been reached."""
        return self.conversations_used >= self.max_conversations
    
    def can_access_demo(self) -> bool:
        """Check if guest can currently access the demo."""
        return self.is_active and not self.is_expired() and not self.is_limit_reached()
    
    def increment_usage(self) -> None:
        """Increment conversation usage counter."""
        self.conversations_used += 1
        self.last_used_at = datetime.now(timezone.utc).replace(tzinfo=None)
    
    def days_remaining(self) -> int:
        """Calculate days remaining until expiry."""
        if self.is_expired():
            return 0
        delta = self.expires_at - datetime.now(timezone.utc).replace(tzinfo=None)
        return max(0, delta.days)
    
    def conversations_remaining(self) -> int:
        """Calculate conversations remaining."""
        return max(0, self.max_conversations - self.conversations_used)
    
    @classmethod
    def generate_access_token(cls) -> str:
        """Generate a secure access token for guest login (legacy)."""
        return secrets.token_urlsafe(32)
    
    @classmethod
    def generate_setup_token(cls) -> str:
        """Generate a secure setup token for initial account activation."""
        return secrets.token_urlsafe(32)
    
    def create_setup_token(self, expires_hours: int = 1) -> str:
        """
        Create a new setup token for account activation.
        
        Args:
            expires_hours: Hours until token expires (default 1 hour for security)
            
        Returns:
            The unhashed token to send in email
        """
        token = secrets.token_urlsafe(32)
        # Store hashed token in database for security
        self.setup_token = hashlib.sha256(token.encode()).hexdigest()
        self.setup_token_expires = (
            datetime.now(timezone.utc) + timedelta(hours=expires_hours)
        ).replace(tzinfo=None)
        return token  # Return unhashed token to send in email
    
    def verify_setup_token(self, token: str) -> bool:
        """
        Verify a setup token for account activation.
        
        Args:
            token: The unhashed token from email link
            
        Returns:
            True if token is valid and not expired
        """
        if not self.setup_token or not self.setup_token_expires:
            return False
        if datetime.now(timezone.utc).replace(tzinfo=None) > self.setup_token_expires:
            return False
        token_hash = hashlib.sha256(token.encode()).hexdigest()
        return secrets.compare_digest(self.setup_token, token_hash)
    
    def invalidate_setup_token(self) -> None:
        """Invalidate setup token after password is set."""
        self.setup_token = None
        self.setup_token_expires = None
    
    def set_password(self, password_hash: str) -> None:
        """
        Set password and activate account.
        
        Args:
            password_hash: Pre-hashed password (bcrypt)
        """
        self.password_hash = password_hash
        self.is_activated = True
        self.invalidate_setup_token()
    
    def has_password(self) -> bool:
        """Check if user has set a password."""
        return self.password_hash is not None and self.is_activated
    
    def regenerate_setup_token(self, expires_hours: int = 1) -> str:
        """
        Regenerate setup token (for resend email functionality).
        Only works if account is not yet activated.
        
        Returns:
            The unhashed token to send in email
        """
        if self.is_activated:
            raise ValueError("Cannot regenerate setup token for activated account")
        return self.create_setup_token(expires_hours)
    
    def __repr__(self) -> str:
        return f"<GuestUser(id={self.id}, email='{self.email}', activated={self.is_activated}, {self.conversations_used}/{self.max_conversations} used)>"


# ============================================================================
# Voice Demo - Appointment Booking System
# ============================================================================


class AppointmentStatus(enum.Enum):
    """Status of an appointment."""
    PENDING = "pending"
    CONFIRMED = "confirmed"
    CANCELLED = "cancelled"
    COMPLETED = "completed"
    NO_SHOW = "no_show"


class DemoCustomer(Base):
    """
    Customer record for voice demo appointment booking.
    
    Stores customer info registered during voice conversations.
    Separate from the main Customer model to keep demo data isolated.
    """
    __tablename__ = "demo_customers"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Customer identity
    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    phone: Mapped[Optional[str]] = mapped_column(String(50), nullable=True, index=True)
    email: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, index=True)
    
    # Additional info
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    preferred_language: Mapped[str] = mapped_column(String(10), default="ar")  # ar, en
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Relationships
    appointments: Mapped[List["DemoAppointment"]] = relationship(
        "DemoAppointment", 
        back_populates="customer", 
        lazy="selectin",
        cascade="all, delete-orphan"
    )
    
    def full_name(self) -> str:
        """Get full name of the customer."""
        return f"{self.first_name} {self.last_name}"
    
    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "first_name": self.first_name,
            "last_name": self.last_name,
            "full_name": self.full_name(),
            "phone": self.phone,
            "email": self.email,
            "preferred_language": self.preferred_language,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
    
    def __repr__(self) -> str:
        return f"<DemoCustomer(id={self.id}, name='{self.full_name()}')>"


class DemoTimeSlot(Base):
    """
    Available time slots for booking appointments.
    
    Pre-populated with available slots that can be booked.
    """
    __tablename__ = "demo_time_slots"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Slot details
    date: Mapped[datetime] = mapped_column(DateTime, nullable=False, index=True)
    start_time: Mapped[str] = mapped_column(String(10), nullable=False)  # "09:00"
    end_time: Mapped[str] = mapped_column(String(10), nullable=False)    # "09:30"
    duration_minutes: Mapped[int] = mapped_column(Integer, default=30)
    
    # Capacity
    max_bookings: Mapped[int] = mapped_column(Integer, default=1)
    current_bookings: Mapped[int] = mapped_column(Integer, default=0)
    
    # Status
    is_available: Mapped[bool] = mapped_column(Boolean, default=True)
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    
    __table_args__ = (
        Index('ix_demo_slots_date_time', 'date', 'start_time'),
    )
    
    # Relationships
    appointments: Mapped[List["DemoAppointment"]] = relationship(
        "DemoAppointment",
        back_populates="time_slot",
        lazy="selectin"
    )
    
    def is_bookable(self) -> bool:
        """Check if slot can be booked."""
        if not self.is_available:
            return False
        if self.current_bookings >= self.max_bookings:
            return False
        # Check if slot is in the future
        slot_datetime = self.date.replace(
            hour=int(self.start_time.split(":")[0]),
            minute=int(self.start_time.split(":")[1])
        )
        return slot_datetime > datetime.now()
    
    def book(self) -> bool:
        """Attempt to book this slot. Returns True if successful."""
        if not self.is_bookable():
            return False
        self.current_bookings += 1
        if self.current_bookings >= self.max_bookings:
            self.is_available = False
        return True
    
    def release(self) -> None:
        """Release a booking from this slot."""
        if self.current_bookings > 0:
            self.current_bookings -= 1
        if self.current_bookings < self.max_bookings:
            self.is_available = True
    
    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "date": self.date.strftime("%Y-%m-%d"),
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration_minutes": self.duration_minutes,
            "is_available": self.is_bookable(),
            "slots_remaining": max(0, self.max_bookings - self.current_bookings),
        }
    
    def __repr__(self) -> str:
        return f"<DemoTimeSlot(id={self.id}, date={self.date.strftime('%Y-%m-%d')}, time={self.start_time}-{self.end_time})>"


class DemoAppointment(Base):
    """
    Appointment booking for voice demo.
    
    Links a customer to a time slot.
    """
    __tablename__ = "demo_appointments"
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign keys
    customer_id: Mapped[int] = mapped_column(
        Integer, 
        ForeignKey("demo_customers.id", ondelete="CASCADE"), 
        nullable=False, 
        index=True
    )
    time_slot_id: Mapped[int] = mapped_column(
        Integer, 
        ForeignKey("demo_time_slots.id", ondelete="CASCADE"), 
        nullable=False, 
        index=True
    )
    
    # Appointment details
    service_type: Mapped[str] = mapped_column(String(100), default="consultation")
    status: Mapped[AppointmentStatus] = mapped_column(
        StringEnumType(AppointmentStatus, name='appointmentstatus'),
        default=AppointmentStatus.PENDING
    )
    
    # Notes from conversation
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Voice session reference
    voice_session_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())
    confirmed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    cancelled_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    
    # Relationships
    customer: Mapped["DemoCustomer"] = relationship("DemoCustomer", back_populates="appointments")
    time_slot: Mapped["DemoTimeSlot"] = relationship("DemoTimeSlot", back_populates="appointments")
    
    def confirm(self) -> None:
        """Confirm the appointment."""
        self.status = AppointmentStatus.CONFIRMED
        self.confirmed_at = datetime.now(timezone.utc).replace(tzinfo=None)
    
    def cancel(self) -> None:
        """Cancel the appointment and release the slot."""
        self.status = AppointmentStatus.CANCELLED
        self.cancelled_at = datetime.now(timezone.utc).replace(tzinfo=None)
        if self.time_slot:
            self.time_slot.release()
    
    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "customer": self.customer.to_dict() if self.customer else None,
            "time_slot": self.time_slot.to_dict() if self.time_slot else None,
            "service_type": self.service_type,
            "status": self.status.value,
            "notes": self.notes,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "confirmed_at": self.confirmed_at.isoformat() if self.confirmed_at else None,
        }
    
    def __repr__(self) -> str:
        customer_name = self.customer.full_name() if self.customer else "Unknown"
        return f"<DemoAppointment(id={self.id}, customer='{customer_name}', status={self.status.value})>"
